# -*- coding: utf-8 -*-
"""HW2_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mGdwektVZwr-nriunYcI4aU5D_cbdL0
"""

# Generating data in Q1
import numpy as np
from matplotlib import pyplot as plt
np.random.seed(0)
n=10
x = np.linspace(0,3,n)
y = 2.0*x + 1.0+ 0.5*np.random.randn(n)
y[9] = 20
plt.plot(x,y,'o')
plt.plot(x,2*x+1)
plt.legend(['data','true line'])
plt.show()


#Question 1 Answer

#Building the input X_tilde with an extra dimension of input for the bias term
X_tilde = np.zeros((2,n))
X_tilde[0,:] = 1
X_tilde[1,:]=x

X_tilde_transpose = np.transpose(X_tilde)

#Using closed form solution to get the optimal w and b values
temp = np.linalg.inv(np.matmul(X_tilde, X_tilde_transpose))
w_tilde =np.matmul(temp, np.matmul(X_tilde, y))

#Gettng the optimal w and b values from w_tilde
w =w_tilde[1]
b=w_tilde[0]
print("The optimal w value using linear regression is " + str(w))
print("The optimal b value using linear regression is " + str(b))

#Constant term
lamda = 3
#2x2 identity matrix
identity_matrix = np.zeros((2,2))
identity_matrix[0,0]=1
identity_matrix[1,1] = 1

#Using closed form solution for ridge regression to get optimal w and b values
temp = np.matmul(X_tilde, X_tilde_transpose) + (lamda*identity_matrix)
temp = np.linalg.inv(temp)
w_tilde_ridgeRegression = np.matmul(temp,np.matmul(X_tilde, y))

#Getting the optimal w and b values from w_tilde_ridgeRegression
w_ridgeRegression = w_tilde_ridgeRegression[1]
b_ridgeRegression = w_tilde_ridgeRegression[0]
print("The optimal w value using ridge regression is " + str(w_ridgeRegression))
print("The optimal b value using ridge regression is " + str(b_ridgeRegression))

plt.plot(x,y,'o')
plt.plot(x,2*x+1)
plt.plot(x, (w * x)+ b)
plt.plot(x, (w_ridgeRegression * x)+ b_ridgeRegression)
plt.legend(['data','true line', 'least mean square solution', 'ridge regression solution'])
plt.xlabel("X values")
plt.ylabel("Y values")
plt.show()


# Generating data in Q2
import numpy as np
from matplotlib import pyplot as plt
np.random.seed(0)
n=10
m=8
x= np.linspace(0,3,50)
x_train = np.linspace(0,3,n)
y_train = -x_train**2 +2*x_train + 2 +0.5*np.random.randn(n)
x_test = np.linspace(0,3,m)
y_test = -x_test**2 +2*x_test + 2 + 0.5*np.random.randn(m)
plt.plot(x_train,y_train,'o')
plt.plot(x_test,y_test,'x')
plt.plot(x,-x**2 +2*x + 2)
plt.legend(['training samples','test samples','true line'])
plt.show()

#Question 2 Answer

# Creating feature transformation for the training data
phi_training = np.zeros((5,n))
phi_training[0,:] = 1
phi_training[1,:]=x_train
phi_training[2,:] = x_train * x_train
phi_training[3,:] = x_train * x_train * x_train
phi_training[4,:] = x_train * x_train * x_train * x_train
phi_training_transpose = np.transpose(phi_training)

# Creating feature transformation for the test data
phi_test = np.zeros((5,m))
phi_test[0,:] = 1
phi_test[1,:]= x_test
phi_test[2,:] = x_test * x_test
phi_test[3,:] = x_test * x_test * x_test
phi_test[4,:] = x_test * x_test * x_test * x_test

#Constant
lamda=0.1
#5x5 identity matrix
identity_matrix = np.zeros((5,5))
identity_matrix[0,0] = 1
identity_matrix[1,1] = 1
identity_matrix[2,2] = 1
identity_matrix[3,3] = 1
identity_matrix[4,4] = 1

#Closed form solution for nonlinear ridge regression
temp = np.matmul(phi_training, phi_training_transpose) + (lamda*identity_matrix)
temp =np.linalg.inv(temp)
w_tilde = np.matmul(temp, np.matmul(phi_training, y_train))

w = w_tilde[1:]
b = w_tilde[0]
print("The optimal w value using ridge regression is " + str(w))
print("The optimal b value using ridge regression is " + str(b))


training_errors = []
test_errors = []
lamdas= []

lamda = 0.0001
#Looping through all values for lamda
for i in range(100):
    #Closed form solution for optimal w using this iteration's lamda value
    temp = np.matmul(phi_training, phi_training_transpose) + (lamda*identity_matrix)
    temp =np.linalg.inv(temp)
    w_tilde = np.matmul(temp, np.matmul(phi_training, y_train))

    #Getting predictions for train and test data using w_tilde
    training_prediction = np.matmul(np.transpose(w_tilde), phi_training)
    test_prediction = np.matmul(np.transpose(w_tilde), phi_test)

    #Calculating the MSE on training data and test data
    training_error= np.sum((y_train - training_prediction) * (y_train - training_prediction))/ n
    test_error= np.sum((y_test - test_prediction) * (y_test - test_prediction))/ m

    #Storing the lamda value, training error, and test error
    training_errors.append(training_error)
    test_errors.append(test_error)
    lamdas.append(lamda)
    #Incrementing lamda
    lamda = lamda+0.001

plt.plot(lamdas, training_errors)
plt.xlabel('Lamda values')
plt.ylabel('The training error')
plt.title("Training error as a function of lambda")
plt.show()

plt.plot(lamdas, test_errors)
plt.xlabel('Lamda values')
plt.ylabel('The test error')
plt.title("Test error as a function of lambda")
plt.show()


# Load Spambase data in Q5
import numpy as np
import urllib.request
from sklearn.model_selection import train_test_split
from scipy.stats import multivariate_normal
url =" http://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
raw_data = urllib.request.urlopen(url)
dataset = np.loadtxt(raw_data,delimiter=",")
x = dataset[:,0:-1]
y = dataset[:,-1]
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size = 0.30, random_state= 17)

#Question 5 Answer

#Training data size
N = len(y_train)
#Number of dimensions in input
d = len(x_train[0])

num_spam = 0
num_notSpam = 0

mean_spam = np.zeros(d)
mean_notSpam = np.zeros(d)

#Looping through training set
for i in range(N):
    if y_train[i] ==1:
        #Updating spam count and mean vector for spam cases, if training case has a label of 1
        num_spam +=1
        mean_spam = mean_spam + x_train[i]
    else:
        #Updating not_spam count and mean vector for not_spam cases, if training case has a label of 0
        num_notSpam +=1
        mean_notSpam = mean_notSpam + x_train[i]

#Creating mean vectors for spam cases and not_spam cases by dividing by total num of spam cases and non spam cases
mean_spam = mean_spam/num_spam
mean_notSpam = mean_notSpam/num_notSpam

#Probabiltiy of spam is number of spam cases in training set divided by training set size
prob_spam = num_spam/N

covariance_matrix = np.zeros((d,d))

#Looping through all training cases
for i in range(N):

    #Getting difference between the input vector x_i and the mean vector corresponding to its label
    if y_train[i]==1:
        temp = x_train[i] - mean_spam
    else:
        temp = x_train[i] - mean_notSpam
    
    temp = temp.reshape(d,1)
    #Summing up the outer product of all these temp vectors
    covariance_matrix += np.matmul(temp, np.transpose(temp))

covariance_matrix = covariance_matrix/N

covariance_matrix_inverse = np.linalg.inv(covariance_matrix)

#Constructing the terms in g(x) formula from slides (used to find posterior class probabiltiy)
term1 = np.matmul(covariance_matrix_inverse, (mean_spam-mean_notSpam))
term1 = np.transpose(term1)

term2 = np.matmul(covariance_matrix_inverse, mean_notSpam)
term2 = 0.5 * np.matmul(np.transpose(mean_notSpam), term2)

term3 = np.matmul(covariance_matrix_inverse, mean_spam)
term3 = -0.5 * np.matmul(np.transpose(mean_spam), term3)

term4 = prob_spam/(1-prob_spam)
term4 = np.log(term4)

combined = term2+term3+term4

num_test = len(y_test)
errors = 0

#Looping through all test cases
for i in range(num_test):
    #Constructing g(x) for this test case
    g_x = np.matmul(term1, x_test[i]) + combined
    
    #Finding probability of spam given input test case
    temp = 1 + np.exp(-1 * g_x)
    prob_spam_given_x = 1/temp

    #Prediction is 1 (spam) if probability>=0.5 and 0 if probability <0.5
    if prob_spam_given_x>=0.5:
        prediction=1
    else:
        prediction = 0
    #Inrementing errors if the prediction is incorrect
    if prediction != y_test[i]:
        errors+=1

test_error = errors/num_test

print("The test error with the LDA classifier for spam filtering is:  " + str(test_error))
